<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>SUMMER INSTITUTE FOR TEACHERS WEB GALLERY | Design-Based Learning Programs | Art Center College of Design</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="robots" content="index,follow" />
<meta name="subject" content="teachers resources, california education standards, critical thinking skills" />
<meta name="owner" content="ACCD Design-Based Learning Lab" />
<meta name="copyright" content="Art Center College of Design" />
<meta name="author" content="C. Spangler Design" />
<meta name="resource-type" content="document" />
<meta name="revisit-after" content="14 days" />
<meta name="classification" content="education, non-profit, college, school" />
<meta name="distribution" content="Global" />
<meta name="rating" content="General" />
<meta name="language" content="en-us" />
<!--[if IE 7]>
<style type="text/css">
.menu li {float:left;}
</style>
<![endif]-->




<link href="css/dbl_styles.css" rel="stylesheet" type="text/css" media="all" />
<style type="text/css">
body {
	background-color: #7ad2f6;
}
</style>
</head>

<body>
<div id="wrapper">
<?php include('includes/masthead.php'); ?>
<?php include('includes/navigation.php'); ?>




<div id="contentArea">

	<h1>Summer Institute for Teachers Web Gallery  </h1>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td valign="top" class="caption"><img src="images/sit057.jpg" width="280" height="280" /><br />
Excite, involve and inspire students. Learn innovative techniques that lead to high achievement on standardized tests.</td>
<td width="20" valign="top">&nbsp;</td>
<td valign="top" class="caption"><img src="images/sit016.jpg" width="280" height="280" /><br />
Hands-on principles are at the heart of Design-Based Learning (DBL). This learn-by-doing method teaches students to understand, connect with and retain the concepts and specifics of the subjects being taught.</td>
</tr>
<tr>
<td valign="top">&nbsp;</td>
<td width="20" valign="top">&nbsp;</td>
<td valign="top">&nbsp;</td>
</tr>
<tr>
<td valign="top" class="caption"><img src="images/sit046.jpg" width="280" height="280" /><br />
The Design-Based Learning approach integrates multiple subjects through the physical creation of the students&rsquo; version of a &ldquo;future&rdquo; neighborhood, community, city or civilization that reflects the mandated curriculum.&nbsp;</td>
<td width="20" valign="top">&nbsp;</td>
<td valign="top" class="caption"><img src="images/sit039.jpg" width="280" height="280" /><br />
Learn time-tested techniques to deliver the standards from practicing classroom teachers of all subjects and grade levels. They walk you through the DBL method they use in their classrooms to increase engagement and raise test scores for their students. They also share items generated by their students during their DBL experience.</td>
</tr>
<tr>
<td valign="top">&nbsp;</td>
<td width="20" valign="top">&nbsp;</td>
<td valign="top">&nbsp;</td>
</tr>
<tr>
<td valign="top" class="caption"><img src="images/sit027.jpg" width="280" height="280" /><br />
After each activity, the teachers create lesson plans that relate the activities to their subject matter and standards.  This direct application of the activities to the teachers&rsquo; individual subject matter and standards is what makes our Institute unique from other professional development programs.<br /></td>
<td width="20" valign="top">&nbsp;</td>
<td valign="top" class="caption"><img src="images/sit056.jpg" width="280" height="280" /><br />
Anyone can apply the Design-Based Learning method without special training in design or the arts. Simple, everyday classroom materials are used.</td>
</tr>
<tr>
<td valign="top">&nbsp;</td>
<td width="20" valign="top">&nbsp;</td>
<td valign="top">&nbsp;</td>
</tr>
<tr>
<td valign="top" class="caption"><img src="images/sit007.jpg" width="280" height="280" /><br />
Since 2002, more than 200 K-12 teachers from 29 different school districts in the greater Los Angeles area and beyond have participated in the Summer Institute for Teachers.</td>
<td width="20" valign="top">&nbsp;</td>
<td valign="top">&nbsp;</td>
</tr>
</table>
</div>
	
</div>
<div id="footer">&copy; Copyright 2017-2018 ArtCenter College of Design.  All Rights Reserved.</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-2285864-31");
pageTracker._trackPageview();
} catch(err) {}</script>


</body>
</html>
